### PR TITLE
Handle correct unicodedata method exception

### LINKED ISSUE #6: Character \x00 in to_ascii() raises an exception
```py
import homoglyphs as hg
hg.Homoglyphs(languages={'en'}, strategy=hg.STRATEGY_LOAD).to_ascii('\x00')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "homoglyphs/core.py", line 240, in to_ascii
    return self.uniq_and_sort(self._to_ascii(text))
  File "homoglyphs/core.py", line 169, in uniq_and_sort
    result = list(set(data))
  File "homoglyphs/core.py", line 235, in _to_ascii
    for variant in self._get_combinations(text, ascii=True):
  File "homoglyphs/core.py", line 218, in _get_combinations
    alt_chars = self._get_char_variants(char)
  File "homoglyphs/core.py", line 195, in _get_char_variants
    if not self._update_alphabet(char):
  File "homoglyphs/core.py", line 182, in _update_alphabet
    category = Categories.detect(char)
  File "homoglyphs/core.py", line 66, in detect
    category = unicodedata.name(char).split()[0]
ValueError: no such name
```
I guess it should rather return `[]`.

(BTW, is this fork still maintained?)

### PR DESCRIPTION
**Pull request by wesinator**
`unicodedata` methods return ValueError, not TypeError. https://docs.python.org/3/library/unicodedata.html
fix #6

@yamatt

[NO_TRAIN]::

### CODE REVIEW

**Comment by yamatt** [comment]
Amazing. Thanks @wesinator this is my first PR since taking over the project. So let me check a few things and I hope to get back to you soon.

**Comment by yamatt** [comment]
So I've had a look around @wesinator.

So I agree with you that exception type should be `ValueError` according to the docs and as in your PR.

Although from testing, what happens is that `unicode.name` does in fact raise a `TypeError` if you enter an empty unicode string.

Then what happens is the `TypeError` is caught, but nothing is done with it except that there's a comment about Python 2. Then it continues on to the section below the error block which then throws another own `TypeError`.

Personally I find the flow in this method a bit strange.

I'm not certain of the intention of this bit of code. Possibly one option is to ensure we have a valid `char` parameter in this function. But I'm also thinking this might mess up some deployments depending on how they defensively they wrote their coding.

Could I ask, if you wouldn't mind, providing a bit more detail on the issue you encountered here? Was it just to align it to the docs? Or were you encountering an error?

**Comment by wesinator** [comment]
> Amazing. Thanks @wesinator this is my first PR since taking over the project. So let me check a few things and I hope to get back to you soon.

#5 was the first?
I think you have to manually follow your own forks to get notified of activity - unfortunately Github doesn't have the fork author automatically follow their own repo yet.

**Comment by wesinator** [comment]
That's interesting that it throws a TypeError, the Python docs don't seem complete.

This was to fix someone else's issue, #6

It looks like the purpose of to_ascii is to convert glyphs to ascii representations - https://github.com/yamatt/homoglyphs/blob/fe302e55a30d4ef19f8d912241b18855911df858/README.md?plain=1#L124

I'll look at updating the PR. Also I'll probably open a python issue for the undocumented `TypeError`, since that also seems odd because other non-empty string types work in that method.

[NO_TRAIN]::

**Pull request merged**
